In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [2]:
df = pd.read_csv("UrbanSound8K.csv")

df.head()


,slice_file_name,fsID,start,end,salience,fold,classID,class
0,100032-3-0-0.wav,100032,0.0,0.317551,1,5,3,dog_bark
1,100263-2-0-117.wav,100263,58.5,62.500000,1,5,2,children_playing
2,100263-2-0-121.wav,100263,60.5,64.500000,1,5,2,children_playing
3,100263-2-0-126.wav,100263,63.0,67.000000,1,5,2,children_playing
4,100263-2-0-137.wav,100263,68.5,72.500000,1,5,2,children_playing


In [3]:
# Selecting features
X = df[['start', 'end', 'salience', 'fold']]

# Target variable
y = df['class']


In [4]:
le = LabelEncoder()
y = le.fit_transform(y)


In [5]:
scaler = StandardScaler()
X = scaler.fit_transform(X)


In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


In [10]:
param_grid = {
    'C': [1, 10],
    'kernel': ['linear'],   # remove rbf for now
}

grid = GridSearchCV(SVC(), param_grid, cv=3)
grid.fit(X_train, y_train)

print("Best Parameters:", grid.best_params_)


Best Parameters: {'C': 10, 'kernel': 'linear'}


In [11]:
best_model = grid.best_estimator_

y_pred = best_model.predict(X_test)


In [12]:
print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.24041213508872353

Confusion Matrix:
 [[  0   0   0   0   0 117   0   6  80   0]
 [  0  18   0  12   4  15   0  11  26   0]
 [  0   0   0   1   2 109   0   0  71   0]
 [  0  10   0  25  14 101   0   1  50   0]
 [  0   1   0  15  21 150   0   6  13   0]
 [  0   0   0   1  11 154   0  11  16   0]
 [  0   6   0  26  20  14   0   0   6   0]
 [  0   3   0   3  18  71   0  82  31   0]
 [  0   1   0   2   1  38   0   3 120   0]
 [  0   0   0   0   3 146   0   5  76   0]]

Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       203
           1       0.46      0.21      0.29        86
           2       0.00      0.00      0.00       183
           3       0.29      0.12      0.17       201
           4       0.22      0.10      0.14       206
           5       0.17      0.80      0.28       193
           6       0.00      0.00      0.00        72
           7       0.66      0.39      0.49       208
       

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
